# 使用的语言
language: node_js

# 使用的nodejs版本
node_js:
 - 4.4.4

# 仓库的分支
branches:
  only:
  - master

# 执行isntall前需要执行的命令
before_install:
# 配置解密信息
 - openssl aes-256-cbc -K $encrypted_b20d7045110e_key -iv $encrypted_b20d7045110e_iv -in id_rsa.enc -out id_rsa -d
  

# 改变文件权限
# - chmod 600 ~/.ssh/id_rsa

# 配置 ssh
 - eval $(ssh-agent)
 - ssh-add ~/.ssh/id_rsa
 - cp .travis/ssh_config ~/.ssh/config

after_script:
 -scp -o StrictHostKeyChecking=no app.js root@47.93.58.173:/root/www/ceshi



