language: node_js
node_js:
- 4.4.4
branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_a84c98bfd8d7_key -iv $encrypted_a84c98bfd8d7_iv
  -in travis.enc -out travis -d

- chmod 600 ~/.ssh/travis

# 配置 ssh

- eval $(ssh-agent)

- ssh-add ~/.ssh/travis

- cp .travis/ssh_config ~/.ssh/config

after_script: 
 -scp -o StrictHostKeyChecking=no app.js root@123.207.233.35:/root/www/ceshi


